/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArrowRightUpIcon: typeof import('tdesign-icons-vue-next')['ArrowRightUpIcon']
    CloudDownloadIcon: typeof import('tdesign-icons-vue-next')['CloudDownloadIcon']
    Footer: typeof import('./components/Footer.vue')['default']
    FooterLogo: typeof import('./components/icon/FooterLogo.vue')['default']
    GitPullRequestFilledIcon: typeof import('tdesign-icons-vue-next')['GitPullRequestFilledIcon']
    HelpCircleFilledIcon: typeof import('tdesign-icons-vue-next')['HelpCircleFilledIcon']
    Loading: typeof import('./components/Loading.vue')['default']
    LogoGithubFilledIcon: typeof import('tdesign-icons-vue-next')['LogoGithubFilledIcon']
    MailIcon: typeof import('tdesign-icons-vue-next')['MailIcon']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Standing: typeof import('./components/Standing.vue')['default']
    StudentItem: typeof import('./components/StudentItem.vue')['default']
    TBaseTable: typeof import('tdesign-vue-next')['BaseTable']
    TButton: typeof import('tdesign-vue-next')['Button']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TeamItem: typeof import('./components/TeamItem.vue')['default']
    TLink: typeof import('tdesign-vue-next')['Link']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
    UsergroupIcon: typeof import('tdesign-icons-vue-next')['UsergroupIcon']
    UserIcon: typeof import('tdesign-icons-vue-next')['UserIcon']
  }
}
